### ISSUE TITLE
Archlinux based distro

### ISSUE THREAD

**Issue by SecT0uch** [hlein/distro-backdoor-scanner#2]
Would it be possible to support archlinux and archlinux-based distributions ? Manjaro, EndeavourOS, etc

**Comment by hlein** [comment]
> Would it be possible to support archlinux and archlinux-based distributions ? Manjaro, EndeavourOS, etc

Should be, actually that's next on my todo list, probably EndeavourOS, now that adding support for RPM family distros is in.

I've updated README/TODO to make it official.
